edit apt-src

diff --git a/apt-src b/apt-src
--- a/apt-src
+++ b/apt-src
@@ -8,12 +8,12 @@ fi
 
 install() {
     if [ $# -lt 2 ]; then
-		echo "Usage: apt-src install <package>"
+	echo "Usage: apt-src install <package>"
         exit 1
     fi
 	[[ -d /tmp/apt-src ]] || mkdir /tmp/apt-src
 	cd /tmp/apt-src
-    apt source install --build "$2" || apt build-dep -yy "$2" && apt source install --build "$2" && dpkg -i "$2"*.deb && echo -e "Package: $2 installed." || echo -e >&2 "Error: $2 is not installed."
+	apt source install --build "$2" || apt build-dep -yy "$2" && apt source install --build "$2" && dpkg -i "$2"*.deb && echo -e "Package: $2 installed." || echo -e >&2 "Error: $2 is not installed."
 }
 
 case "$1" in
@@ -21,9 +21,9 @@ case "$1" in
         install "$@"
         ;;
     *)
-		echo "Usage: apt-src install <package>"
-		echo "Example: apt-src install hello"
-		exit 1
+	echo "Usage: apt-src install <package>"
+	echo "Example: apt-src install hello"
+	exit 1
         ;;
 esac
 
